// examples/vue/src/components/Widget.vue
<template>
  <Widget :config="config" />
</template>

<script lang="ts">
// This is a React component
import { EVMProvider } from '@lifi/wallet-provider-evm'
import { LiFiWidget } from '@lifi/widget'
import { applyPureReactInVue } from 'veaury'

export default {
  components: {
    // Use HOC 'applyReactInVue' or 'applyPureReactInVue'
    // Basic: applyReactInVue(LiFiWidget),
    Widget: applyPureReactInVue(LiFiWidget),
  },
  setup() {
    return {
      config: {
        theme: {
          container: {
            border: '1px solid rgb(234, 234, 234)',
            borderRadius: '16px',
          },
        },
        integrator: 'vue-example',
        providers: [EVMProvider()],
      },
    }
  },
}
</script>

// examples/nextjs14/components/Widget.tsx
'use client'

import { EVMProvider } from '@lifi/wallet-provider-evm'
import type { WidgetConfig } from '@lifi/widget'
import { LiFiWidget, WidgetSkeleton } from '@lifi/widget'
import { ClientOnly } from './ClientOnly'

export function Widget() {
  const config = {
    appearance: 'light',
    theme: {
      container: {
        border: '1px solid rgb(234, 234, 234)',
        borderRadius: '16px',
      },
    },
  } as Partial<WidgetConfig>

  return (
    <ClientOnly fallback={<WidgetSkeleton config={config} />}>
      <LiFiWidget
        config={config}
        integrator="nextjs-example"
        providers={[EVMProvider()]}
      />
    </ClientOnly>
  )
}
