// examples/nuxt-v2/components/LiFiWidget.vue
<template>
  <lifi-widget :config="config" />
</template>

<script>
import { LiFiWidget } from '@lifi/widget';

export default {
  components: { 'lifi-widget': LiFiWidget },
  data() {
    return {
      config: {
        containerStyle: {
          border: `1px solid rgb(234, 234, 234)`,
          borderRadius: '16px',
        },
      }
    }
  },
}
</script>

// examples/svelte/src/lib/LiFiWidget.svelte
<script>
  import { LiFiWidget } from '@lifi/widget';
  import ReactAdapter from './ReactAdapter.svelte';
</script>

<ReactAdapter
  element={LiFiWidget}
  config={{
    containerStyle: {
      border: `1px solid rgb(234, 234, 234)`,
      borderRadius: '16px',
    },
  }}
/>

<style>
  /**
   * Styling a React Component from within a Svelte Component.
   */
</style>
